### ISSUE TITLE
Doesn't sign transaction for fungible tokens/coins 

### ISSUE THREAD

**Issue by HaiderShahid** [WietseWind/xrpl-accountlib#307]
Hi, 
I am unable to sign the transaction when using fungible tokens 

e.g

      const sendTokenTx = {
        TransactionType: 'Payment',
        Amount: {
          currency: currencyCode,
          value: amount.toString(),
          issuer: lenderBotWallet.address
        },
        Account: senderWallet.address,
        Destination: receiverWallet.address,
        Memos: memos.map(memo => ({
          Memo: {
            MemoData: stringToHex(memo.text),
            MemoFormat: stringToHex('text/plain'),
            MemoType: stringToHex(memo.header)
          }
        })),
        Fee:12,
        Sequence: account_data.Sequence

      }

I am not able to sign the above transaction. Is this library available only for XRP and no other custom fungible token ?

**Comment by WietseWind** [comment]
Unable to sign in what way? What happens? What's the error?

First thing that strikes me as off is the fact that the `Fee` is a Number instead of a String (string with XRP drops).
